obj-y += abox_util.o abox_dbg.o abox_dump.o abox_log.o abox_gic.o
obj-y += abox.o abox_rdma.o abox_wdma.o abox_if.o abox_effect.o
obj-y += abox_vss.o abox_failsafe.o abox_vdma.o abox_mmapfd.o
obj-$(CONFIG_SEC_SND_ADAPTATION) += abox_adaptation.o
