/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Copyright (C) 2026 Mathias Gluszczynski <admin@krazey.de>
 *
 * Device Tree binding constants for the Exynos9810 clock controller.
 */

#ifndef _DT_BINDINGS_CLOCK_SAMSUNG_EXYNOS9810_H
#define _DT_BINDINGS_CLOCK_SAMSUNG_EXYNOS9810_H

/* CMU_TOP */
#define CLK_GOUT_TOP_CMGP_BUS			1
#define CLK_GOUT_TOP_DPU_BUS			2

/* CMU_FSYS0 */
#define CLK_MOUT_FSYS0_BUS_USER			1
#define CLK_MOUT_FSYS0_UFS_EMBD_USER		2
#define CLK_GOUT_FSYS0_UFS_EMBD_ACLK		3
#define CLK_GOUT_FSYS0_UFS_EMBD_UNIPRO		4
#define CLK_MOUT_FSYS0_USB30DRD_USER		5
#define CLK_GOUT_FSYS0_USB30DRD_LINK		6
#define CLK_GOUT_FSYS0_USB30DRD_REF		7
#define CLK_GOUT_FSYS0_USB30DRD_CTRL		8

/* CMU_FSYS1 */
#define CLK_MOUT_FSYS1_BUS_USER			1
#define CLK_MOUT_FSYS1_PCIE_USER			2
#define CLK_GOUT_FSYS1_PCIE_PHY_REF		3
#define CLK_GOUT_FSYS1_PCIE_DBI			4
#define CLK_GOUT_FSYS1_PCIE_PHY_APB		5
#define CLK_GOUT_FSYS1_PCIE_MSTR			6
#define CLK_GOUT_FSYS1_PCIE_SUBCTRL		7
#define CLK_GOUT_FSYS1_PCIE_PCS			8
#define CLK_GOUT_FSYS1_PCIE_SLV			9

/* CMU_PERIC0 */
#define CLK_MOUT_PERIC0_BUS_USER			1
#define CLK_MOUT_PERIC0_IP_USER			2
#define CLK_GOUT_PERIC0_UART_DBG			3
#define CLK_DOUT_PERIC0_UART_DBG			4
#define CLK_GOUT_PERIC0_UART_DBG_RST		5
#define CLK_GOUT_PERIC0_UART_DBG_PCLK		6
#define CLK_GOUT_PERIC0_UART_DBG_IPCLK		7
#define CLK_GOUT_PERIC0_USI3_QCH			8
#define CLK_GOUT_PERIC0_USI3			9
#define CLK_DOUT_PERIC0_USI3			10
#define CLK_GOUT_PERIC0_USI3_RST			11
#define CLK_GOUT_PERIC0_USI3_IPCLK		12
#define CLK_GOUT_PERIC0_USI3_PCLK		13

/* CMU_CMGP */
#define CLK_MOUT_CMGP_BUS_USER			1
#define CLK_GOUT_CMGP_USI3_QCH			2
#define CLK_MOUT_CMGP_USI3			3
#define CLK_GOUT_CMGP_USI3			4
#define CLK_DOUT_CMGP_USI3			5
#define CLK_GOUT_CMGP_USI3_RST			6
#define CLK_GOUT_CMGP_USI3_IPCLK			7
#define CLK_GOUT_CMGP_USI3_PCLK			8

/* CMU_DPU */
#define CLK_MOUT_DPU_BUS_USER			1
#define CLK_GOUT_DPU_SYSMMU_DPUD1_PCLK		2
#define CLK_GOUT_DPU_SYSMMU_DPUD1_QCH		3

/* ACPM DVFS */
#define CLK_ACPM_DVFS_MIF			0
#define CLK_ACPM_DVFS_INT			1
#define CLK_ACPM_DVFS_CPUCL0			2
#define CLK_ACPM_DVFS_CPUCL1			3
#define CLK_ACPM_DVFS_G3D			4
#define CLK_ACPM_DVFS_INTCAM			5
#define CLK_ACPM_DVFS_FSYS0			6
#define CLK_ACPM_DVFS_CAM			7
#define CLK_ACPM_DVFS_DISP			8
#define CLK_ACPM_DVFS_AUD			9
#define CLK_ACPM_DVFS_IVA			10
#define CLK_ACPM_DVFS_SCORE			11
#define CLK_ACPM_DVFS_CP			12

#endif /* _DT_BINDINGS_CLOCK_SAMSUNG_EXYNOS9810_H */
